spring.application.name=huddle

# .env loading
spring.config.import=optional:file:.env[.properties]

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:huddle}
spring.datasource.username=${DB_USERNAME:huddle_app}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
