-- ---------------------------------------------------------------------------
-- Enum types
-- ---------------------------------------------------------------------------
CREATE TYPE club_status          AS ENUM ('active', 'inactive');
CREATE TYPE club_interest_source AS ENUM ('campusgroups', 'inferred', 'manual');
CREATE TYPE club_link_type       AS ENUM ('instagram', 'facebook', 'x', 'linkedin', 'youtube', 'tiktok', 'discord', 'linktree', 'website');
CREATE TYPE post_media_type      AS ENUM ('image', 'video', 'carousel', 'reel');
CREATE TYPE event_source         AS ENUM ('instagram', 'campusgroups', 'manual');
CREATE TYPE scrape_status        AS ENUM ('pending', 'running', 'success', 'failure');

-- ---------------------------------------------------------------------------
-- Shared update trigger
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- clubs
-- ---------------------------------------------------------------------------
CREATE TABLE clubs (
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                 uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    slug                      text NOT NULL UNIQUE,
    status                    club_status NOT NULL DEFAULT 'active',
    name                      text NOT NULL,
    description               text,
    campusgroups_id           text NOT NULL UNIQUE,
    mission                   text,
    goals                     text,
    club_type                 text,
    membership_type           text,
    contacts                  jsonb,
    instagram_handle          text,
    follower_count            int,
    activity_score            real,
    last_scraped_at           timestamptz,
    logo_url                  text,
    search_vector             tsvector GENERATED ALWAYS AS (
                                  setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
                                  setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
                                  setweight(to_tsvector('english', coalesce(mission, '')), 'C') ||
                                  setweight(to_tsvector('english', coalesce(goals, '')), 'C')
                              ) STORED,
    created_at                timestamptz NOT NULL DEFAULT now(),
    updated_at                timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_clubs_slug_format     CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT ck_clubs_name_nonempty   CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_clubs_contacts_array  CHECK (contacts IS NULL OR jsonb_typeof(contacts) = 'array'),
    CONSTRAINT ck_clubs_handle_format   CHECK (instagram_handle ~ '^[a-z0-9._]+$'),
    CONSTRAINT ck_clubs_follower_count  CHECK (follower_count >= 0),
    CONSTRAINT ck_clubs_activity_score  CHECK (activity_score BETWEEN 0 AND 100)
);

CREATE INDEX idx_clubs_name          ON clubs (name);
CREATE INDEX idx_clubs_search_vector ON clubs USING gin (search_vector);

CREATE TRIGGER trg_clubs_set_updated_at
    BEFORE UPDATE ON clubs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    email                   text NOT NULL UNIQUE,
    google_sub              text NOT NULL UNIQUE,
    full_name               text,
    avatar_url              text,
    onboarding_completed_at timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_email_cornell CHECK (
        email = lower(email) AND email ~ '^[^@[:space:]]+@cornell\.edu$'
    ),
    CONSTRAINT ck_users_full_name_nonempty CHECK (length(btrim(full_name)) > 0)
);

CREATE TRIGGER trg_users_set_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- refresh_tokens
--
-- Opaque refresh tokens, stored only as a SHA-256 hash (base64url) so a database
-- leak doesn't yield usable tokens. Rows are append-only apart from revoked_at.
-- family_id groups a rotation chain: presenting an already-rotated token is
-- treated as theft and revokes the whole family.
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint      NOT NULL,
    token_hash text        NOT NULL UNIQUE,
    family_id  uuid        NOT NULL,
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_refresh_tokens_hash_nonempty CHECK (length(btrim(token_hash)) > 0),
    CONSTRAINT ck_refresh_tokens_expiry        CHECK (expires_at > created_at)
);

CREATE INDEX idx_refresh_tokens_user   ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_family ON refresh_tokens (family_id);

-- ---------------------------------------------------------------------------
-- interests
-- ---------------------------------------------------------------------------
CREATE TABLE interests (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug     text NOT NULL UNIQUE,
    name     text NOT NULL,
    CONSTRAINT ck_interests_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT ck_interests_name_nonempty CHECK (length(btrim(name)) > 0)
);

-- ---------------------------------------------------------------------------
-- club_interests
-- ---------------------------------------------------------------------------
CREATE TABLE club_interests (
    club_id     bigint NOT NULL,
    interest_id bigint NOT NULL,
    source      club_interest_source NOT NULL,
    PRIMARY KEY (club_id, interest_id),
    CONSTRAINT fk_club_interests_club
        FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE CASCADE,
    CONSTRAINT fk_club_interests_interest
        FOREIGN KEY (interest_id) REFERENCES interests (id) ON DELETE CASCADE
);

CREATE INDEX idx_club_interests_interest ON club_interests (interest_id);

-- ---------------------------------------------------------------------------
-- user_interests
-- ---------------------------------------------------------------------------
CREATE TABLE user_interests (
    user_id     bigint   NOT NULL,
    interest_id bigint   NOT NULL,
    priority    smallint NOT NULL DEFAULT 1,
    PRIMARY KEY (user_id, interest_id),
    CONSTRAINT fk_user_interests_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_interests_interest
        FOREIGN KEY (interest_id) REFERENCES interests (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_interests_priority CHECK (priority BETWEEN 1 AND 3)
);

CREATE INDEX idx_user_interests_interest ON user_interests (interest_id);

-- ---------------------------------------------------------------------------
-- saved_clubs
-- ---------------------------------------------------------------------------
CREATE TABLE saved_clubs (
    user_id    bigint NOT NULL,
    club_id    bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, club_id),
    CONSTRAINT fk_saved_clubs_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_clubs_club
        FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE CASCADE
);

CREATE INDEX idx_saved_clubs_club ON saved_clubs (club_id);

-- ---------------------------------------------------------------------------
-- club_links
-- ---------------------------------------------------------------------------
CREATE TABLE club_links (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id bigint         NOT NULL,
    type    club_link_type NOT NULL,
    url     text           NOT NULL,
    CONSTRAINT fk_club_links_club
        FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE CASCADE,
    CONSTRAINT uq_club_links_club_type UNIQUE (club_id, type),
    CONSTRAINT ck_club_links_url CHECK (url ~ '^https?://')
);

-- ---------------------------------------------------------------------------
-- instagram_posts
-- ---------------------------------------------------------------------------
CREATE TABLE instagram_posts (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id       bigint         NOT NULL,
    ig_post_id    text           NOT NULL UNIQUE,
    permalink     text           NOT NULL,
    like_count    int            NOT NULL,
    comment_count int            NOT NULL,
    caption       text,
    media_type    post_media_type NOT NULL,
    media_url     text           NOT NULL,
    thumbnail_url text,
    posted_at     timestamptz    NOT NULL,
    scraped_at    timestamptz    NOT NULL DEFAULT now(),
    CONSTRAINT fk_instagram_posts_club
        FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE CASCADE,
    CONSTRAINT ck_instagram_posts_permalink_nonempty CHECK (length(btrim(permalink)) > 0),
    CONSTRAINT ck_instagram_posts_like_count    CHECK (like_count >= 0),
    CONSTRAINT ck_instagram_posts_comment_count CHECK (comment_count >= 0),
    CONSTRAINT ck_instagram_posts_media_url_nonempty CHECK (length(btrim(media_url)) > 0)
);

CREATE INDEX idx_instagram_posts_club_posted ON instagram_posts (club_id, posted_at);

-- ---------------------------------------------------------------------------
-- events
-- ---------------------------------------------------------------------------
CREATE TABLE events (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id             uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    club_id               bigint       NOT NULL,
    title                 text         NOT NULL,
    description           text,
    starts_at             timestamptz  NOT NULL,
    ends_at               timestamptz,
    location              text,
    source                event_source NOT NULL DEFAULT 'instagram',
    source_post_id        bigint,
    extraction_confidence real,
    event_key             text         NOT NULL UNIQUE,
    created_at            timestamptz  NOT NULL DEFAULT now(),
    updated_at            timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_events_club
        FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE CASCADE,
    CONSTRAINT fk_events_source_post
        FOREIGN KEY (source_post_id) REFERENCES instagram_posts (id) ON DELETE SET NULL,
    CONSTRAINT ck_events_title_nonempty   CHECK (length(btrim(title)) > 0),
    CONSTRAINT ck_events_ends_after_start CHECK (ends_at IS NULL OR ends_at >= starts_at),
    CONSTRAINT ck_events_confidence_range CHECK (extraction_confidence BETWEEN 0 AND 1),
    CONSTRAINT ck_events_key_nonempty     CHECK (length(btrim(event_key)) > 0)
);

CREATE INDEX idx_events_club_starts ON events (club_id, starts_at);
CREATE INDEX idx_events_starts      ON events (starts_at);
CREATE INDEX idx_events_source_post ON events (source_post_id);

CREATE TRIGGER trg_events_set_updated_at
    BEFORE UPDATE ON events
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- scrape_runs
-- ---------------------------------------------------------------------------
CREATE TABLE scrape_runs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id     bigint        NOT NULL,
    status      scrape_status NOT NULL,
    started_at  timestamptz   NOT NULL DEFAULT now(),
    finished_at timestamptz,
    posts_found int           NOT NULL DEFAULT 0,
    posts_new   int           NOT NULL DEFAULT 0,
    error       text,
    CONSTRAINT fk_scrape_runs_club
        FOREIGN KEY (club_id) REFERENCES clubs (id) ON DELETE CASCADE,
    CONSTRAINT ck_scrape_runs_finished_time CHECK (finished_at IS NULL OR finished_at >= started_at),
    CONSTRAINT ck_scrape_runs_posts_found   CHECK (posts_found >= 0),
    CONSTRAINT ck_scrape_runs_posts_new     CHECK (posts_new >= 0 AND posts_new <= posts_found)
);

CREATE INDEX idx_scrape_runs_club_started ON scrape_runs (club_id, started_at);
CREATE INDEX idx_scrape_runs_status       ON scrape_runs (status);